type Infographic {
    id: ID!
    title: String!
    author: String!
    shortDescription: String!
    readingTime: Int
}

type User { 
    name: String!
    username: String!
    email: String
    role: String!
}

type Dataset {
    id: ID!
    name: String!
    author: String!
    link: String!
    category: [Category]
}

type Category {
    id: ID!
    name: String!
    cover: String
}

type GeneralResponse {
    message: String!
}

type AuthenticationResponse {
    access_token: String
    user: User
    message: String!
}

input Profile { 
    name: String
    username: String
    password: String
    email: String
    role: String
}

input CategoryInput {
    name: String
    cover: String
}

type Query {
    getInfographic(
        id: ID
        title: String
    ): [Infographic]
    
    getLembaga(
        id: ID,
        name: String
    ): [User]

    getCategory: [Category]
}

type Mutation {
    # Start Infographic Section
    addInfographic(
        title: String!
        author: String!
        shortDescription: String!
        readingTime: Int!
    ): GeneralResponse!

    editInfographic(
        id: ID!
        title: String
        author: String
        shortDescription: String
        readingTime: Int
    ): GeneralResponse!

    deleteInfographic(
        title: String!
    ): GeneralResponse!
    # End Infographic Section

    # Start Authentication Section
    login(
        username: String!
        password: String!
    ): AuthenticationResponse!
    
    register(
        username: String!
        email: String!
        role: String
        password: String!
    ): GeneralResponse!

    verifyPassword(
        username: String!
        password: String!
    ): Boolean!

    editProfile(
        username: String!
        profile: Profile!
    ): GeneralResponse!
    # End Authentication Section

    # Start Category Section
    addCategory(
        name: String!
        cover: String
    ): GeneralResponse!

    editCategory(
        name: String!
        data: CategoryInput!
    ): GeneralResponse!

    deleteCategory(
        name: String!
    ): GeneralResponse!
    # End Category Section

    # Start Dataset Section
    
    # End Dataset Section
}