type Infographic {
    id: ID!
    title: String!
    author: String!
    shortDescription: String!
    readingTime: Int
}

type User { 
    name: String!
    username: String!
    email: String
    role: String!
    hp: String
}

type Dataset {
    id: ID!
    name: String!
    author: String!
    link: String!
    category: [String]
}

type Category {
    id: ID!
    name: String!
    cover: String
}

type GeneralResponse {
    message: String!
}

type AuthenticationResponse {
    access_token: String
    user: User
    message: String!
}

input Profile { 
    name: String
    username: String
    password: String
    email: String
    role: String
    hp: String
}

input CategoryInput {
    name: String
    cover: String
}

input InfographicInput {
    title: String
    author: String
    shortDescription: String
    readingTime: Int
}

input DatasetInput {
    name: String
    author: String
    link: String
    category: [String]
}

type Query {
    getInfographic(
        id: ID
        title: String
    ): [Infographic]

    getDataset(
        id: ID
        name: String
    ): [Dataset]
    
    getLembaga(
        id: ID,
        name: String
    ): [User]

    getCategory: [Category]
}

type Mutation {
    # Start Infographic Section
    addInfographic(
        title: String!
        author: String!
        shortDescription: String!
        readingTime: Int!
    ): GeneralResponse!

    editInfographic(
        title: String!
        data: InfographicInput!
    ): GeneralResponse!

    deleteInfographic(
        title: String!
    ): GeneralResponse!
    # End Infographic Section

    # Start Authentication Section
    login(
        username: String!
        password: String!
    ): AuthenticationResponse!
    
    register(
        username: String!
        email: String
        role: String
        password: String!
        hp: String
    ): GeneralResponse!

    verifyPassword(
        username: String!
        password: String!
    ): Boolean!

    editProfile(
        username: String!
        profile: Profile!
    ): GeneralResponse!
    # End Authentication Section

    # Start Category Section
    addCategory(
        name: String!
        cover: String
    ): GeneralResponse!

    editCategory(
        name: String!
        data: CategoryInput!
    ): GeneralResponse!

    deleteCategory(
        name: String!
    ): GeneralResponse!
    # End Category Section

    # Start Dataset Section
    addDataset(
        name: String!
        author: String!
        link: String!
        category: [String]!
    ): GeneralResponse!

    editDataset(
        name: String!
        data: DatasetInput!
    ): GeneralResponse!

    deleteDataset(
        name: String!
    ): GeneralResponse!
    # End Dataset Section
}