type Infographic {
    id: ID!
    title: String!
    author: String!
    shortDescription: String!
    readingTime: Int
}

type User { 
    name: String!
    username: String!
    role: String!
}

type Dataset {
    id: ID!
    name: String!
    author: String!
    link: String!
    category: [Category]
}

type Category {
    id: ID!
    name: String!
    cover: String
}

type GeneralResponse {
    status: Int!
    message: String!
}

type AuthenticationResponse {
    access_token: String
    user: User
    message: String!
}

type Query {
    getInfographics: [Infographic]
    getInfographic(id: ID!): Infographic
    countInfographic: GeneralResponse

    getLembaga: [User]

    countDataset: GeneralResponse

    getCategory: [Category]
}

type Mutation {
    # Start Infographic Section
    addInfographic(
        title: String
        author: String
        shortDescription: String
        readingTime: Int
    ): GeneralResponse!

    editInfographic(
        id: ID!
        title: String
        author: String
        shortDescription: String
        readingTime: Int
    ): GeneralResponse!

    deleteInfographic(
        id: ID!
    ): GeneralResponse!
    # End Infographic Section

    # Start Authentication Section
    login(
        username: String!
        password: String!
    ): AuthenticationResponse!
    
    signup(
        username: String!
        password: String!
    ): GeneralResponse!

    forgotPassword(
        username: String!
    ): GeneralResponse!

    editProfile(
        username: String!
        password: String!
    ): GeneralResponse!
    # End Authentication Section

    # Start Category Section
    addCategory(
        name: String!
        cover: String
    ): GeneralResponse!

    editCategory(
        id: ID!
        name: String
        cover: String
    ): GeneralResponse!

    deleteCategory(
        id: ID!
    ): GeneralResponse!
    # End Category Section

    # Start Dataset Section
    
    # End Dataset Section
}